name: Deploy static site to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SCP
        run: |
          scp -r ./ root@159.65.42.248:/var/www/html

      - name: Restart Nginx
        run: |
          ssh root@159.65.42.248 'systemctl restart nginx'
